### PR TITLE
PEP8 load.py, remove overly-aggressive KeyError.

### PR DESCRIPTION
**Pull request by TkTech**
I thought about leaving the KeyError exception in there, but can see no point to it - it doesn't look like it's ever been catching what it was meant to since it fails at an earlier step.

### CODE REVIEW

**Comment by wardi** [comment]
:+1: I should have reviewed this change more closely. Please fix the test and I'll merge

**Comment by TkTech** [comment]
@wardi I am tempted to remove the failing test completely, since it's intentionally causing the KeyError by sending a "corrupted" resource. We probably want this to happen since otherwise you have no idea what field is missing.

**Comment by wardi** [comment]
@TkTech I want the error to appear like a validation error from ckan, not cause a whole "load datasets" command to fail out in the middle.

**Comment by wardi** [comment]
@TkTech do you have time to fix this?

**Comment by wardi** [comment]
I take it #77 is the new version of this PR

**Comment by TkTech** [comment]
@wardi I believe he accidentally included it. I'll take some time today to finish this.

**Comment by wardi** [comment]
I've already started working on this yesterday. There's *lots* I want to change about how the uploading is handled, and I want to add some actual tests of the functionality.

**Comment by TkTech** [comment]
Even better!

**Comment by wardi** [comment]
removed this KeyError as part of #78 . proper fixes for uploading code to come later

**Pull request closed without merging**
