### PR TITLE
Added the option to pass -1 to --max_rows too load all data

### PR DESCRIPTION
**Pull request by LaurentGoderre**

### CODE REVIEW

**Comment by wardi** [comment]
you can already omit the --max-rows option to get the same effect. What's the purpose of this change?

**Comment by LaurentGoderre** [comment]
In a batch script, instead of doing (pseudo code)

```
if max_result
    ckanapi load -I file1.json
    ckanapi load -I file2.json
    ...
else
    ckanapi load -I file1.json -m $max_result
    ckanapi load -I file2.json -m $max_result
    ...
```

You can do

```
max_result = max_result or -1

ckanapi load -I file1.json -m $max_result
ckanapi load -I file2.json -m $max_result
 ...
```

**Comment by wardi** [comment]
Bash lets you include the whole option as a variable, e.g.

```sh
[ -z "$max_result" ] || max_option="-m $max_result"

ckanapi load datasets -I file1.json $max_option 
```

Also, nothing about "-1" says "all the rows", so this would be a hidden obscure feature that would confuse people.

**Comment by LaurentGoderre** [comment]
It's pretty common for a maximum argument to accept -1 as meaning unbound but alright...

**Comment by wardi** [comment]
common and terrible.

This kind of pattern leads to really surprising problems when people use code to calculate the number of rows without proper bounds checking, which is also really common. I try not to design interfaces that fail spectacularly when used incorrectly :-)

**Pull request closed without merging**
